# Generated by Django 5.2.14 on 2026-06-21 12:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_demo_description_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demopoint',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
